name: Generate Resource Packs Release

on:
  push:
    branches: [main]

jobs:
  build_and_release:
    name: Build and Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP archives from directories
        run: |
          find . -mindepth 2 -maxdepth 2 -type d | while read -r directory; do
            zip -r "$directory.zip" "$directory"
          done
        shell: bash

      - name: View the resource packs you created
        run: find . -maxdepth 1 -type f -name "*.zip"

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
