name: Generate Resource Packs Release

on:
  push:
    branches: [main]

jobs:
  build_and_release:
    name: Build and Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Find manifest or minigame files and create ZIP archives
        run: |
          find . -mindepth 2 -maxdepth 2 -type f \( -name 'manifest.json' -o -name 'minigame.json' \) | while read -r file; do
            directory=$(dirname "$file")
            cd "$directory" || exit
            zip -r "$PWD/$(basename "$directory").zip" .
            cd - || exit
          done
        shell: bash

      - name: View the resource packs you created
        run: find . -maxdepth 1 -type f -name "*.zip"

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
